In [1]:
import tensorflow as tf

In [2]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [4]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [5]:
for sales in tf_dataset.take(4).as_numpy_iterator():
    print(sales)

21
22
-108
31


In [6]:
tf_dataset = tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
34
31


In [7]:
tf_dataset = tf_dataset.map(lambda x: x*72)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2232
2304
2448
2232


In [9]:
tf_dataset = tf_dataset.shuffle(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

2232
1512
2304
1584
2232
2448


In [10]:
for sales_batch in tf_dataset.batch(2):
    print(sales_batch.numpy())

[1584 1512]
[2448 2304]
[2232 2232]


In [11]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(2).batch(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1584 2232]
[1512 2448]
[2232 2304]


In [12]:
images_ds = tf.data.Dataset.list_files('images/*/*', shuffle=False)

In [13]:
image_count = len(images_ds)
image_count

130

In [14]:
type(images_ds)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [15]:
for file in images_ds.take(3):
    print(file.numpy())

b'images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg'
b'images\\cat\\7 Foods Your Cat Can_t Eat.jpg'
b'images\\cat\\A cat appears to have caught the....jpg'


In [16]:
images_ds = images_ds.shuffle(200)
for file in images_ds.take(3):
    print(file.numpy())

b'images\\cat\\Cat Throwing Up_ Normal or Cause for....jpg'
b'images\\cat\\International Cat Care _ The ultimate....jpg'
b'images\\cat\\Cats Care About People More Than Food....jpg'


In [17]:
class_names = ["cat","dog"]

In [18]:
train_size = int(image_count*0.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [19]:
len(train_ds)

104

In [20]:
len(test_ds)

26

In [21]:
def get_label(file_path):
    import os
    parts = tf.strings.split(file_path, os.path.sep)
    return parts[-2]

In [22]:
get_label("images\\dog\\20 Reasons Why Cats Make the Best Pets....jpg")

<tf.Tensor: shape=(), dtype=string, numpy=b'dog'>

In [23]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path) # load the raw data from the file as a string
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128, 128])
    return img, label

In [24]:
img, label = process_image("images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg")
img.numpy()[:2]

array([[[155.      , 186.      , 215.      ],
        [156.      , 187.      , 216.      ],
        [158.      , 189.      , 218.      ],
        [160.0039  , 189.0039  , 219.0039  ],
        [161.0039  , 190.0039  , 220.0039  ],
        [162.      , 191.      , 221.      ],
        [166.      , 193.      , 222.      ],
        [167.      , 194.      , 223.      ],
        [168.      , 195.      , 224.      ],
        [169.      , 196.      , 225.      ],
        [170.      , 197.      , 224.      ],
        [170.0039  , 197.0039  , 224.0039  ],
        [172.      , 199.      , 226.      ],
        [173.0039  , 199.0039  , 224.0039  ],
        [174.0039  , 200.0039  , 225.0039  ],
        [175.0039  , 201.0039  , 226.0039  ],
        [176.      , 202.      , 227.      ],
        [177.0039  , 203.0039  , 228.0039  ],
        [177.0039  , 203.0039  , 228.0039  ],
        [179.0039  , 203.0039  , 227.0039  ],
        [180.0039  , 204.0039  , 228.0039  ],
        [180.0039  , 204.0039  , 2

In [25]:
train_ds = train_ds.map(process_image)
test_ds = test_ds.map(process_image)

In [26]:
for image, label in train_ds.take(1):
    print("****",image)
    print("****",label)

**** tf.Tensor(
[[[ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  ...
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]]

 [[ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  ...
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]]

 [[ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  ...
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]]

 ...

 [[ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  ...
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]]

 [[ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  ...
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]]

 [[ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  ...
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]
  [ 82.  82.  82. 255.]]], shape=(128, 128, 4), dtype=float32)
**** tf.Tensor(b'cat', shape=

In [27]:
def scale(image, label):
    return image/255, label

In [28]:
train_ds = train_ds.map(scale)

In [29]:
for image, label in train_ds.take(5):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())

****Image:  [0.7316167  0.74805355 0.75981826]
****Label:  b'dog'
****Image:  [0.7538603  0.76954657 0.8166054 ]
****Label:  b'dog'
****Image:  [0.08627451 0.08627451 0.08627451]
****Label:  b'dog'
****Image:  [0.8784314  0.90588236 0.94509804]
****Label:  b'cat'
****Image:  [0.99607843 0.99607843 0.99607843]
****Label:  b'dog'
